version: '3.9'
services:
  metabase:
    image: metabase/metabase-enterprise:v1.48.8
    container_name: metabase
    hostname: metabase
    ports:
      - 3000:3000
    volumes: 
      - /dev/urandom:/dev/random:ro
    environment: 
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 6432
      MB_DB_USER: metabase
      MB_DB_PASS: mysecretpassword
      MB_DB_HOST: pgbouncer-app-db
    cpus: 1
    mem_limit: 2048m
    networks: 
      - metanet1
    depends_on: 
      postgres-app-db:
        condition: service_healthy
      postgres-data1:
        condition: service_healthy
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  pgbouncer-app-db:
    image: bitnami/pgbouncer:1.22.1
    hostname: pgbouncer-app-db
    environment:
      - POSTGRESQL_USERNAME=metabase
      - POSTGRESQL_PASSWORD=mysecretpassword
      - POSTGRESQL_DATABASE=metabase
      - POSTGRESQL_HOST=postgres-app-db
      - POSTGRESQL_PORT=5432
      - PGBOUNCER_PORT=6432
      - PGBOUNCER_IGNORE_STARTUP_PARAMETERS=extra_float_digits
      - PGBOUNCER_DATABASE=metabase
    networks: 
      - metanet1
  postgres-app-db:
    image: postgres:16.1-alpine
    container_name: postgres-app-db
    hostname: postgres-app-db
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_USER=metabase"
      - "POSTGRES_DB=metabase"
      - "POSTGRES_PASSWORD=mysecretpassword"
    # volumes:
    #   - $PWD/postgres_origin:/var/lib/postgresql/data
    networks: 
      - metanet1
    cpus: 1
    mem_limit: 128m
    # command: -c log_statement=all
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase -d metabase"]
      interval: 10s
      timeout: 5s
      retries: 5
  setup:
    image: bash:5.2.15
    container_name: setup
    volumes:
      - $PWD/setup:/tmp
    networks:
      - metanet1
    depends_on:
      metabase:
        condition: service_healthy
    command: sh /tmp/metabase-setup.sh metabase:3000
    cpus: 1
    mem_limit: 128m
  pgbouncer-data-db:
    image: bitnami/pgbouncer:1.22.1
    hostname: pgbouncer-data-db
    environment:
      - POSTGRESQL_USERNAME=metabase
      - POSTGRESQL_PASSWORD=metasample123
      - POSTGRESQL_DATABASE=sample
      - POSTGRESQL_HOST=postgres-data1
      - POSTGRESQL_PORT=5432
      - PGBOUNCER_PORT=6432
      - PGBOUNCER_DATABASE=sample
      - PGBOUNCER_IGNORE_STARTUP_PARAMETERS=extra_float_digits
    networks: 
      - metanet1
  postgres-data1:
    image: metabase/qa-databases:postgres-sample-12
    container_name: postgres-data1
    ports:
      - 5434:5432
    hostname: postgres-data1
    networks: 
      - metanet1
    cpus: 4
    mem_limit: 128m
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase -d sample"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: -c log_statement=all
networks: 
  metanet1:
    driver: bridge
